// flow-typed signature: 4e49db6c9f7e1b52e73b75e6b3676a89
// flow-typed version: <<STUB>>/apollo-server-core_v3.3.0/flow_v0.159.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server-core/dist/ApolloServer' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/cachePolicy' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/determineApolloConfig' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/graphqlOptions' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/internalPlugin' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/nodeHttpToRequest' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/cacheControl' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/drainHttpServer' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/drainHttpServer/stoppable' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/inlineTrace' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/landingPage/default' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/landingPage/graphqlPlayground' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/schemaIsFederated' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/schemaReporting' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/schemaReporting/schemaReporter' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/traceTreeBuilder' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting/defaultSendOperationsAsTrace' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting/durationHistogram' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting/iterateOverTrace' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting/options' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting/plugin' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting/signatureCache' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting/stats' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/plugin/usageReporting/traceDetails' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/requestPipeline' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/runHttpQuery' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/types' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/utils/createSHA' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/utils/dispatcher' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/utils/isNodeLike' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/utils/pluginTestHarness' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/utils/schemaHash' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/utils/schemaInstrumentation' {
  declare module.exports: any;
}

declare module 'apollo-server-core/dist/utils/schemaManager' {
  declare module.exports: any;
}

declare module 'apollo-server-core/src/plugin/drainHttpServer/__tests__/stoppable/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server-core/dist/ApolloServer.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/ApolloServer'>;
}
declare module 'apollo-server-core/dist/cachePolicy.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/cachePolicy'>;
}
declare module 'apollo-server-core/dist/determineApolloConfig.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/determineApolloConfig'>;
}
declare module 'apollo-server-core/dist/graphqlOptions.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/graphqlOptions'>;
}
declare module 'apollo-server-core/dist/index' {
  declare module.exports: $Exports<'apollo-server-core/dist'>;
}
declare module 'apollo-server-core/dist/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist'>;
}
declare module 'apollo-server-core/dist/internalPlugin.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/internalPlugin'>;
}
declare module 'apollo-server-core/dist/nodeHttpToRequest.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/nodeHttpToRequest'>;
}
declare module 'apollo-server-core/dist/plugin/cacheControl/index' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/cacheControl'>;
}
declare module 'apollo-server-core/dist/plugin/cacheControl/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/cacheControl'>;
}
declare module 'apollo-server-core/dist/plugin/drainHttpServer/index' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/drainHttpServer'>;
}
declare module 'apollo-server-core/dist/plugin/drainHttpServer/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/drainHttpServer'>;
}
declare module 'apollo-server-core/dist/plugin/drainHttpServer/stoppable.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/drainHttpServer/stoppable'>;
}
declare module 'apollo-server-core/dist/plugin/index' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin'>;
}
declare module 'apollo-server-core/dist/plugin/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin'>;
}
declare module 'apollo-server-core/dist/plugin/inlineTrace/index' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/inlineTrace'>;
}
declare module 'apollo-server-core/dist/plugin/inlineTrace/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/inlineTrace'>;
}
declare module 'apollo-server-core/dist/plugin/landingPage/default/index' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/landingPage/default'>;
}
declare module 'apollo-server-core/dist/plugin/landingPage/default/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/landingPage/default'>;
}
declare module 'apollo-server-core/dist/plugin/landingPage/graphqlPlayground/index' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/landingPage/graphqlPlayground'>;
}
declare module 'apollo-server-core/dist/plugin/landingPage/graphqlPlayground/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/landingPage/graphqlPlayground'>;
}
declare module 'apollo-server-core/dist/plugin/schemaIsFederated.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/schemaIsFederated'>;
}
declare module 'apollo-server-core/dist/plugin/schemaReporting/index' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/schemaReporting'>;
}
declare module 'apollo-server-core/dist/plugin/schemaReporting/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/schemaReporting'>;
}
declare module 'apollo-server-core/dist/plugin/schemaReporting/schemaReporter.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/schemaReporting/schemaReporter'>;
}
declare module 'apollo-server-core/dist/plugin/traceTreeBuilder.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/traceTreeBuilder'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/defaultSendOperationsAsTrace.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting/defaultSendOperationsAsTrace'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/durationHistogram.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting/durationHistogram'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/index' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/index.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/iterateOverTrace.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting/iterateOverTrace'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/options.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting/options'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/plugin.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting/plugin'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/signatureCache.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting/signatureCache'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/stats.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting/stats'>;
}
declare module 'apollo-server-core/dist/plugin/usageReporting/traceDetails.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/plugin/usageReporting/traceDetails'>;
}
declare module 'apollo-server-core/dist/requestPipeline.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/requestPipeline'>;
}
declare module 'apollo-server-core/dist/runHttpQuery.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/runHttpQuery'>;
}
declare module 'apollo-server-core/dist/types.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/types'>;
}
declare module 'apollo-server-core/dist/utils/createSHA.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/utils/createSHA'>;
}
declare module 'apollo-server-core/dist/utils/dispatcher.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/utils/dispatcher'>;
}
declare module 'apollo-server-core/dist/utils/isNodeLike.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/utils/isNodeLike'>;
}
declare module 'apollo-server-core/dist/utils/pluginTestHarness.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/utils/pluginTestHarness'>;
}
declare module 'apollo-server-core/dist/utils/schemaHash.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/utils/schemaHash'>;
}
declare module 'apollo-server-core/dist/utils/schemaInstrumentation.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/utils/schemaInstrumentation'>;
}
declare module 'apollo-server-core/dist/utils/schemaManager.js' {
  declare module.exports: $Exports<'apollo-server-core/dist/utils/schemaManager'>;
}
declare module 'apollo-server-core/src/plugin/drainHttpServer/__tests__/stoppable/server.js' {
  declare module.exports: $Exports<'apollo-server-core/src/plugin/drainHttpServer/__tests__/stoppable/server'>;
}
